### ISSUE TITLE
Suggest to add type=int for batch_size and num_layers args

### ISSUE THREAD

**Issue by wanghm92** [Tiiiger/bert_score#1]
When passing an argument such as 

`bert-score -r refs.txt -c hyps.txt --bert bert-base-uncased -b 4`

will cause the following error, since the 4 is interpreted as str

`line 147, in bert_cos_score_idf
    for batch_start in range(0, len(refs), batch_size):
TypeError: 'str' object cannot be interpreted as an integer`.

adding `type=int` should resolve the issue.

Thanks!

**Comment by felixgwu** [comment]
Hi @wanghm92,

Thanks a lot for pointing this out. I've fixed it.

Best,
Felix
