### ISSUE TITLE
Can this score evaluate sentence similarity (including semantics)?

### ISSUE THREAD

**Issue by ChenZhongFu** [Tiiiger/bert_score#10]
If I want to evaluate the similarity of two sentences, can I use the score?

**Comment by tianyi-asapp** [comment]
Technically yes, as we used BERTScore to evaluate paraphrase similarity in the [paper](https://arxiv.org/abs/1904.09675). 

You can simply keep the inputs the same. Higher BERTScore means the inputs are more similar.

**Comment by Tiiiger** [comment]
Technically yes, as we used BERTScore to evaluate paraphrase similarity in the [paper](https://arxiv.org/abs/1904.09675). 

You can simply keep the inputs the same. Higher BERTScore means the inputs are more similar.

**Comment by ChenZhongFu** [comment]
> Technically yes, as we used BERTScore to evaluate paraphrase similarity in the [paper](https://arxiv.org/abs/1904.09675).
> 
> You can simply keep the inputs the same. Higher BERTScore means the inputs are more similar.

thank you very much!!

**Comment by Tiiiger** [comment]
I am closing this. Please feel free to reopen this if you have any further questions.
