### ISSUE TITLE
Calculate P but the result of the paper is different

### ISSUE THREAD

**Issue by EchoFei333** [Tiiiger/bert_score#102]
Hello, when I use the WMT2017 data set to reproduce the BertScore method, the P(RoBERTa-Large(idf)) obtained in many data sets (such as fi-en, lv-en, etc.) is quite different from the value in the paper. I have checked all the details but it did not affect the results I got, so I want to ask you for help, hoping to solve the problem.
For example,among them, my actual calculations are in parenthesesfi-en：0.975（0.966）lv-en：0.935（0.908）......

**Comment by felixgwu** [comment]
Hi @EchoFei333, 

Are you able to reproduce the same numbers without idf or even with idf but on other language pairs?
It is possible that the idf_dict is not computed correctly on some datasets. 
We compute the idf_dict for each language pair separately.

**Comment by felixgwu** [comment]
Hi @EchoFei333,

We put a script to reproduce WMT17 system-level results to this [folder](https://github.com/Tiiiger/bert_score/tree/master/reproduce). 

After this command in the `reproduce` folder:
```sh
bash download_wmt17.sh
python get_wmt17_sys_results.py -b 16 --model roberta-large --idf
```
You will get the following outputs:
```
model_type,cs-en,de-en,fi-en,lv-en,ru-en,tr-en,zh-en,avg
roberta-large P (idf),0.9894973500365629,0.9594570437659099,0.9749506488405805,0.935433504994967,0.943965485991742,0.9679643023753896,0.9735477138162407,0.9635451499744848
roberta-large R (idf),0.9949002773976816,0.9909641685636977,0.9616421726152359,0.9794914071304269,0.980946167535508,0.9814022049918295,0.9702992241997808,0.9799493746334514
roberta-large F (idf),0.9961450050990823,0.9824078132653736,0.9975307488103976,0.9910181879158707,0.9648212941684465,0.9913921343262727,0.9841596167469899,0.9867821143332048
```

**Comment by EchoFei333** [comment]
Hi,@felixgwu,

Thank you very much for your prompt and careful reply. When I am using the Bert-Base model (with idf and without idf), the results I got were consistent with those in the paper. Thank you for your suggestions. I will Keep using your method with the Bert-Base model.
I will use the file you provided to review the results. The information you provided is great and solved my problem.Thank you again.

**Comment by Tiiiger** [comment]
closing. seems like the issue has been addressed.
