### ISSUE TITLE
Find relevant word embeddings given a reference word

### ISSUE THREAD

**Issue by Tushar-Faroque** [Tiiiger/bert_score#104]
Hello, Thanks to all for your work.

I want to find relevant words given a reference word and a large text, i.e. "Cats" is the reference word. Now I want to find word embeddings related to cats.

How can I do this. Can you give me some guidelines?

**Comment by Tiiiger** [comment]
Not sure if I understand your questions. 

I figure your use case is probably quite different from the usual use case for BERTScore. So you might want to ask some more general forum like the transformer repo forum. 

check this out:
https://discuss.huggingface.co/
