### ISSUE TITLE
Empty candidate sentence

### ISSUE THREAD

**Issue by achingacham** [Tiiiger/bert_score#107]
Hi,

Could someone help me understand why is the BERTScore recall is non zero when there is an empty candidate sentence. Isn't zero the right score for precision as well as recall over here?

`score([''], ['hello how are you'], lang='en')`

This is what the model returns now:

`Warning: Empty candidate sentence detected; setting precision to be 0.`
`(tensor([0.]), tensor([0.7738]), tensor([0.]))`

best,
Anupama

_Originally posted by @achingacham in https://github.com/Tiiiger/bert_score/issues/62#issuecomment-885983471_

**Comment by felixgwu** [comment]
Hi @achingacham,

Good catch! Thanks a lot! It comes from the fact that the recall uses the [CLS] and [EOS] tokens added to the empty sentences, so the scores are not zero. However, I believe it is more reasonable to set it as zero. I have fixed this bug in a new commit [b1a346](https://github.com/Tiiiger/bert_score/commit/b1a346cce87634c28b616ee5dcdfa33ec306f20c).

Best,
Felix
