### ISSUE TITLE
turkish bert support

### ISSUE THREAD

**Issue by fcakyon** [Tiiiger/bert_score#108]
@Tiiiger @felixgwu thanks a lot for this awesome package!

Do you have any plans to add support for Turkish BERT versions?
https://huggingface.co/dbmdz/bert-base-turkish-cased
https://huggingface.co/dbmdz/distilbert-base-turkish-cased

**Comment by felixgwu** [comment]
Hi @fcakyon,

I have added Turkish BERT support in a new [commit](https://github.com/Tiiiger/bert_score/commit/a6e0427bf51d98537f80aee5c8466c13780607f7).
The performance of each model is presented in this [sheet](https://docs.google.com/spreadsheets/d/1RKOVpselB98Nnh_EOC4A2BYn8_201tmPODpNWu4w7xI/edit#gid=1258809664). I hope this helps.

Best,
Felix
