### ISSUE TITLE
Random sequences giving a higher F1 than real sentences

### ISSUE THREAD

**Issue by Dom1984** [Tiiiger/bert_score#109]
I have been calculating BERTScores for sequences of text, but the model appears to assign a higher BERTScore to random text than to real sequences., For example below:

Example 1:
sent1 = "The man walked down the road"
sent2 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaa"

P, R, F1 = score(sent1, sent2, lang="en", verbose=True)
print(F1.mean()) # 0.8046

Example 2:

sent1 = "An inconsequential super hero and an insignificant super villain do battle on the streets of New York."
sent2 = "Both are the greatest heroes in their time. Both are the greatest villains in their time. They've done"

P, R, F1 = score(sent1, sent2, lang="en", verbose=True) # FIRSTLY CHECK THE PROMPT AGAINST FIRST SUBSTRING
print(F1.mean()) # 0.6883

I can't figure out why a nonsense sentence achieves a higher F1 score. Can anyone assist? Many thanks

**Comment by fcakyon** [comment]
@Dom1984 im really wondering the explanation behind this

**Comment by Dom1984** [comment]
I believe that I've found a solution (of sorts) to this problem.

The mistake I was making was using strings as arguments to the model, when in fact they should be list items containing strings.

So instead of this:

sent1 = "An inconsequential super hero and an insignificant super villain do battle on the streets of New York."
sent2 = "Both are the greatest heroes in their time. Both are the greatest villains in their time. They've done"

I do this:

sent1 = ["An inconsequential super hero and an insignificant super villain do battle on the streets of New York."]
sent2 = ["Both are the greatest heroes in their time. Both are the greatest villains in their time. They've done"]

Another improvement is to rescale, by adding: 
rescale_with_baseline=True 

to the score calculation.

**Comment by fcakyon** [comment]
How are the results changing after this update?

**Comment by Dom1984** [comment]
Without rescaling: 

sent1 = ["An inconsequential super hero and an insignificant super villain do battle on the streets of New York."]
sent2 = ["Both are the greatest heroes in their time. Both are the greatest villains in their time. They've done"]
P, R, F1 = score(sent1, sent2, lang="en", verbose = True ) 
print(F1.mean())  #0.8645

sent1 = ["The man walked down the road"]
sent2 = ["aaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
P, R, F1 = score(sent1, sent2, lang="en", verbose = True ) 
print(F1.mean()) #0.7541

With rescaling:

sent1 = ["An inconsequential super hero and an insignificant super villain do battle on the streets of New York."]
sent2 = ["Both are the greatest heroes in their time. Both are the greatest villains in their time. They've done"]
P, R, F1 = score(sent1, sent2, lang="en", rescale_with_baseline=True) 
print(F1.mean()) # 0.1970

sent1 = ["The man walked down the road"]
sent2 = ["aaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
P, R, F1 = score(sent1, sent2, lang="en", rescale_with_baseline=True) 
print(F1.mean()) # -0.4570

**Comment by fcakyon** [comment]
@Dom1984 thanks a lot!
