### ISSUE TITLE
Script to reporoduce segemet-level WMT17

### ISSUE THREAD

**Issue by long21wt** [Tiiiger/bert_score#110]
Hi,

Can you provide the script to reproduce segment-level result for WMT17 dataset ?

Thanks

**Comment by Tiiiger** [comment]
hi @long21wt 

https://github.com/Tiiiger/bert_score/tree/master/reproduce

I think you can modify the scripts provided in this link. The data format from WMT17 and WMT18 should be similar.

**Comment by long21wt** [comment]
Actually, the segment score format of WMT17 is different in comparison to WMT18 and further dataset. Anyway, I found a solution to compute the segment-level score for WMT17.
