### ISSUE TITLE
Request for the data in Image Captioning experiment, again

### ISSUE THREAD

**Issue by bigbrother001** [Tiiiger/bert_score#116]
I'm so sorry to bother you, but none of the url in https://github.com/Tiiiger/bert_score/issues/22 is available for me, would you like to show some other way to get the dataset and human judgement for me? Thanks a lot.

**Comment by bigbrother001** [comment]
I think it might because I live in China

**Comment by Tiiiger** [comment]
hi @bigbrother001 

can you send me (tz58@stanford.edu) an email and I can email you the data.
