### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by irejwan** [Tiiiger/bert_score#119]
Thanks for the repo! it's very useful and I appreciate it alot.
It would be great if you include an option to calculate the BERTScore between every pair of sentences between two list of sentences. Right now I'm using a workaround by duplicating the sentences to create all the possible pairs, but it is very wasteful since the embeddings for every sentence are calculated a number of times instead of only once.
Also, it would be helpful if you allow calculating the score between partial sentences, that is, embed the full input and output sentences, but align only a partial sequence of tokens defined by the users.

**Comment by irejwan** [comment]
I dived into the code and saw that the workaround I use is fine, because there is a stage of dropping duplicates before calculating the embeddings.

**Comment by Tiiiger** [comment]
Hi @irejwan 

yea you are correct. Internally we deduplicate the embeddings so it should be efficient enough for you application.
