### ISSUE TITLE
Reproduce COCO captioning results

### ISSUE THREAD

**Issue by xu1998hz** [Tiiiger/bert_score#121]
Hi Authors,

Thank you for your great work.  I recently tried to reproduce the COCO image captioning results. However, I had a very different results. I believed this is my setting issue. I followed this link  https://drive.google.com/file/d/1HUrcgLXTNUY9ZbJ6eegb2V92Hfh17j9e to obtain all the validation outputs (files starts as captions_val2014 and ends with results.json). In the paper, you guys stated you only used 12 submissions out of those 15 in the google drive. Would you mind to specify which 12?

**Comment by felixgwu** [comment]
Hi @xu1998hz,

Sorry for the late response. Here are the 12 submissions and their names on the COCO leaderboard that we used.
```
{'kolarmartin': 'Brno University',
 'karpathy': 'NeuralTalk',
 'rakshithShetty': 'PicSOM',
 'junhuaMao': 'm-RNN',
 'OriolVinyals': 'Google',
 'myamaguchi': 'MIL',
 'Q.Wu': 'ACVT',
 'jeffdonahue': 'Berkeley LRCN',
 'mRNN_Share.JMao': 'm-RNN',
 'TsinghuaBigeye': 'Tsinghua Bigeye',
 'ryank': 'MLBL',
 'kelvin_xu': 'Montreal/Toronto'}
```

We dropped `MSR_Captivator`, `mmitchell`, and `NearestNeighbor`
If you check the their predictions, you'll find that the validation captions are missing and they just put the filenames as the captions. 
```sh
$ head MSR_Captivator/captions_val2014_d-me.dmsm.grnn.fc6.fc7.cider.pos.600best_results.json
[{
	"image_id":		560222,
	"caption":		"560222"
},
{
	"image_id":		468354,
	"caption":		"468354"
},
{
	"image_id":		44165,
	
$ head mmitchell/captions_val2014_oldVGG_results.json
[{
	"image_id":		391895,
	"caption":		"391895"
},
{
	"image_id":		522418,
	"caption":		"522418"
},
{
	"image_id":		184613,

$ head NearestNeighbor/captions_val2014_knncider_results.json
[{
	"image_id":		560222,
	"caption":		"560222"
},
{
	"image_id":		468354,
	"caption":		"468354"
},
{
	"image_id":		44165,
```

Best,
Felix
