### ISSUE TITLE
can bertscore be -ve? 

### ISSUE THREAD

**Issue by TarangRanpara** [Tiiiger/bert_score#122]
I'm using 'microsoft/deberta-large-mnli' for computing the score using 'rescale_with_baseline' = True and bertscore is producing a negative similarity result. isn't it supposed to be between 0-1?

**Comment by Tiiiger** [comment]
hi @TarangRanpara 

originally BERTScore is bounded between 1 and -1. After rescaling, it is upperbounded by 1 but not lowerbounded by a specific number (the bound depends on the baseline you rescale it with). 

The baseline rescaling step is linear and only intended for improving readability. Without the rescaling, the output score numbers are often very similar to each other up till the third or fourth digit. 

Hope this answer your question.
