### ISSUE TITLE
Pairwise score

### ISSUE THREAD

**Issue by JAugusto97** [Tiiiger/bert_score#123]
Hey,

I need to calculate the bert_score in a pairwise fashion for a dataset. In your examples, you provide two files that are related line-by-line, but I want to calculate the score from the first sentence to all the other sentences, then the score for the second sentence to all the other sentences and so on.

What I did was: created a "refs.txt" file replicating sentence 1 N times (N is the size of the dataset) and a file "cands.txt" with all N sentences. I did this process for all the sentences in my dataset, concatenating them in these files. Now I can run the score command on those big files.

Is this a valid approach to solve my problem?
Thanks!

**Comment by Tiiiger** [comment]
hi @JAugusto97 

yes this approach is what I would recommend. Internally, BERTScore deduplicate the inputs so doing this doesn't blow up computation time.

closing but feel free to follow up with questions you may have

**Comment by JAugusto97** [comment]
I'm still having trouble with RAM actually, 12GB (google collab) was not enough. I assume changing batch_size won't help since this is not GPU memory. 🤔

**Comment by JAugusto97** [comment]
sampled 5k sentences and now it's running but I'm using 21gbs of RAM while the model runs
