### ISSUE TITLE
text similarity between word “happy” and "sad"

### ISSUE THREAD

**Issue by shaoniana1997** [Tiiiger/bert_score#126]
Hello, if i want to calculate the text semantic simliarity between word "happy" and "sad" 
do you have another other nice choices except "bert-score"？？？？
@felixgwu

**Comment by Tiiiger** [comment]
hi @shaoniana1997 

I think just using the cosine similarity between the word embeddings would be find.

**Comment by ivanstepanovftw** [comment]
Google for sbert
