### ISSUE TITLE
weights of the model checkpoint at roberta-large

### ISSUE THREAD

**Issue by giuseppeboezio** [Tiiiger/bert_score#129]
I have the following problem:
after calling the score function in the following way
`score([candidate], [reference], lang='en', rescale_with_baseline=True)`
I get the following warning

> Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight'] - This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model). - This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

I get the outputs of the function but how can I fix this problem?

**Comment by felixgwu** [comment]
Hi @giuseppeboezio,

This is a warning from huggingface's transformers library that simply reminds people in case they do something unintended. You can ignore this warning since this is expected. Those weights won't be used in BERTScore computation.

**Comment by giuseppeboezio** [comment]
Ok, I see now, thank you so much
