### ISSUE TITLE
Syntax error in utils.py

### ISSUE THREAD

**Issue by peterjliu** [Tiiiger/bert_score#13]
https://github.com/Tiiiger/bert_score/blob/master/bert_score/utils.py#L215

`P, R, F1 = greedy_cos_idf(*ref_stats, *hyp_stats)`

is a syntax error. You can change it to:

```
stats = ref_stats + hyp_stats
P, R, F1 = greedy_cos_idf(*stats)
```

**Comment by Tiiiger** [comment]
Hi, thank you for letting us know. Are you running the codes with Python2?

We have done our implementation in python3 and I will specify that in the README.

**Comment by peterjliu** [comment]
Hi, it looks like this syntax was introduced in python 3.5, not 3.0

  https://legacy.python.org/dev/peps/pep-0448/

Can you make it clear which python version you're using?

**Comment by Tiiiger** [comment]
Just specified in the README that this repo quires python >= 3.6.
