### ISSUE TITLE
lang=en-sci error

### ISSUE THREAD

**Issue by zhhhzhang** [Tiiiger/bert_score#131]
when I set lang="en-sci", there is an error as follows:

Traceback (most recent call last):
  File "bertscore_snipp.py", line 39, in <module>
    P, R, F1 = scorer.score(cands, refs)
  File "/home/zzh/zzhenv/lib/python3.6/site-packages/bert_score/scorer.py", line 232, in score
    all_preds = (all_preds - self.baseline_vals) / (1 - self.baseline_vals)
  File "/home/zzh/zzhenv/lib/python3.6/site-packages/bert_score/scorer.py", line 151, in baseline_vals
    raise ValueError(f"Baseline not Found for {self.model_type} on {self.lang} at {self.baseline_path}")
ValueError: Baseline not Found for allenai/scibert_scivocab_uncased on en-sci at /home/zzh/zzhenv/lib/python3.6/site-packages/bert_score/rescale_baseline/en-sci/allenai/scibert_scivocab_uncased.tsv

I don't konw why? when I set lang='zh', it is OK

**Comment by felixgwu** [comment]
Hi @zhhhzhang,
The reason for seeing this issue is that we currently don't support `en-sci` with `rescale_with_baseline=True`.
You can either set it to False or wait a little bit. I'll compute the baseline score and update our repo recently.

**Comment by felixgwu** [comment]
I have added the baseline scores in `bert_score/rescale_baseline/en-sci/allenai/scibert_scivocab_uncased.tsv` which should fix the ValueError you got if you install bert_score in the master branch. I hope this solves your problem.
