### ISSUE TITLE
The computation method when dealing with multiple references

### ISSUE THREAD

**Issue by kumori123** [Tiiiger/bert_score#136]
Hi，
I‘m now doing research on a text generation task called text simplification, in which it's common that there are multiple references for a single output. I noticed that BertScore now seems to be able to deal with this case, and I'm curious about the computation method. Maybe taking average for each BertScore calculated from a output/ref pairs is the operation in current version?
Thank you !

**Comment by Tiiiger** [comment]
Hi 

This is computed by taking the mean of all output/ref pairs.
