### ISSUE TITLE
About the definition of Precision and Recall in BERTScore

### ISSUE THREAD

**Issue by thangld201** [Tiiiger/bert_score#139]
Hi, I'm a bit curious on how the Precision & Recall is defined in BERTScore. Although I've read through the papers several times, the designs of Precision & Recall in BERTScore still look vague to me. <br/> Specifically, in the paper, Precision is calculated by, for each token representation in the reference, compute its max dot product with a token in the candidate, then take the average sum. Meanwhile, Recall is calculated by, for each token representation in the candidate, compute its max dot product with a token in the reference, then take the average sum. <br/> I'm a bit confused on how these formulas should be treated as Precision and Recall. Particularly, in this way, Precision is viewed as how well the reference's tokens are reflected in the candidate, whereas Recall is viewed as how well the candidate's tokens reflect the reference's, which both seem like standard Recall metrics. Furthermore, the Precision is computed by averaging the length of the reference, contrary to ROUGE (Precision by averaging length of the candidate). <br/> Would you mind clarifying on the design of Precision and Recall in BERTScore ?

**Comment by thangld201** [comment]
@felixgwu Could you further explain this part ? As it wasn't included in the paper, if I'm not wrong.

**Comment by Tiiiger** [comment]
hi BERTScore precision is dividing the length of candidate. in the paper notation x_hat is the candidate.

**Comment by thangld201** [comment]
Thanks for the reply, I realized I mistook the notations :))
