### ISSUE TITLE
Getting "nan" as the score 

### ISSUE THREAD

**Issue by amarasovic** [Tiiiger/bert_score#14]
For candidate and reference list of size 1, I get as a results `tensor([nan])`. Is this expected behavior? 

This is the code that results in `nan`:
```
from bert_score import score 

cands = ['28-year-old chef found dead in San Francisco mall']

refs = ['A 28-year-old chef who had recently moved to San Francisco was found dead in the stairwell of a local mall this week.']

_, _, F1 = score(cands, refs, bert="bert-base-uncased", verbose=True)
print (F1)
```

**Comment by felixgwu** [comment]
Hi @amarasovic,
Yes, this is expected. Please set `no_idf=True` instead. (Please also see #6 and #8)
