### ISSUE TITLE
BERTScore complexity ?

### ISSUE THREAD

**Issue by thangld201** [Tiiiger/bert_score#141]
Hi there, I'm a bit curious about BERTScore's time & space complexity, in terms of Big(O) notations. As these can give more theoretical insights for comparing different evaluation metrics' complexity, would you mind clarifying on this @felixgwu ? Thanks a lot.

**Comment by Tiiiger** [comment]
It depends on which step of the process you are thinking. 

Ultimately, most of the memory and computation is spend on computing the BERT (or other models' embedding) and the rest is negligible.

**Comment by thangld201** [comment]
Thanks, I have another question about the area chair's reponse in ICLR 2020 review with respect to your [paper.](https://openreview.net/forum?id=SkeHuCVFDr) ```b) whether second order similarity, e.g., using RSA, would be better than alignment-based similarity;```. Would you mind elaborating on what does he/she mean by second order similarity / RSA here ? I'm not familiar with these and are quite confused @Tiiiger
