### ISSUE TITLE
Use fine tuned model

### ISSUE THREAD

**Issue by seyyedjavadrazavi** [Tiiiger/bert_score#142]
I fine-tuned the bert model on my pc, then used the `bert-score -r comments.txt -c all_tags.txt --model my_model --num_layers 9` code to use the fine-tuned model on bert score, but this error happened.

![image](https://user-images.githubusercontent.com/43475004/202433266-9aa7e262-4a7f-4e66-aa48-36d104acdd4d.png)

**Comment by Tiiiger** [comment]
hi @seyyedjavadrazavi ,

This is saying you didn't give it the correct path to the model folder. Please check you can load your model correctly by
```
from transformers import AutoModel

AutoModel.from_pretrained("<your model>")
```

**Comment by seyyedjavadrazavi** [comment]
Thanks for the quick reply.
I am new to this field and to fine-tune the bert used  [#61](https://github.com/Tiiiger/bert_score/issues/61), [#12](https://github.com/Tiiiger/bert_score/issues/12), and [#82](https://github.com/Tiiiger/bert_score/issues/82) and finally because I want to fine-tune the bert in an unsupervised way,  I used [this link](https://www.analyticsvidhya.com/blog/2022/09/fine-tuning-bert-with-masked-language-modeling/) and `torch.save(model, 'C:/Users/Seyyed Javad Razavi/Desktop/New folder (2)/f_tune_analyticsvidhya/model_2')` code to save the fine-tuned model which saved just a file with the name 'model_2' without any config file.
Now the problem is the code you mentioned is not work for me and this error happened.

![image](https://user-images.githubusercontent.com/43475004/202669534-546f1213-8c3b-4bc9-97e7-2a526169ea79.png)

**Comment by seyyedjavadrazavi** [comment]
Thanks.
I did that and load the fine-tuned model by `model = AutoModel.from_pretrained("./new_model/model/", from_tf=True)` and used the score function `    P, R, F1 = score(crnt_tg, tags_name, model_type = model, num_layers = 10, device="cuda:0")`, but the error was :

![image](https://user-images.githubusercontent.com/43475004/202809237-47659db1-6386-4260-a501-b7d9d437925f.png)

**Comment by felixgwu** [comment]
Hi @seyyedjavadrazavi ,

The argument `model_type` should be a string, please try this:
```
P, R, F1 = score(crnt_tg, tags_name, model_type = "./new_model/model/", num_layers = 10, device="cuda:0")
```

**Comment by seyyedjavadrazavi** [comment]
@felixgwu
Thanks a lot. 
It works now.
