### ISSUE TITLE
exception when passing numpy arrays as inputs

### ISSUE THREAD

**Issue by sanderland** [Tiiiger/bert_score#144]
I ran into the error

"numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U221'), dtype('<U1038'))"

This occurs in 
`sentences = dedup_and_sort(refs + hyps)` in utils.py

I think numpy is trying to do a pairwise concatenation here.

A workaround was to convert both my inputs to normal python lists.

A change to something like

`sentences = dedup_and_sort([*refs, *hyps])`

Appears to fix this and make bert-score happy to take either lists or numpy arrays.

**Comment by felixgwu** [comment]
Hi @sanderland,

Thanks for your suggestion, we will try this and consider supporting this in a new version.
