### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443)

### ISSUE THREAD

**Issue by TristanAlkaid** [Tiiiger/bert_score#145]
Hi,
I just want to run the bertsore offline, so I set the `model_type` to the local path of the downloaded model. The model isBert-base-chinese. Here is how I set the `model_type`.
```
def get_model(model_type, num_layers, all_layers=None):
    if model_type.startswith("scibert"):
        model = AutoModel.from_pretrained(cache_scibert(model_type))
    elif "t5" in model_type:
        from transformers import T5EncoderModel

        model = T5EncoderModel.from_pretrained(model_type)
    else:
        model = AutoModel.from_pretrained("/home/zxy/SportsSum/model/")
    model.eval()

    if hasattr(model, "decoder") and hasattr(model, "encoder"):
        model = model.encoder
```
However, it could run at first, and then it occured a error at the halfway through the program. It seems like the program didn't run offline. The error may appear in `AutoTokenizer.from_pretrained`, but I don't know how to modify it.
```
def get_tokenizer(model_type, use_fast=False):
    if model_type.startswith("scibert"):
        model_type = cache_scibert(model_type)

    if version.parse(trans_version) >= version.parse("4.0.0"):
        tokenizer = AutoTokenizer.from_pretrained(model_type, use_fast=True)
    else:
        assert not use_fast, "Fast tokenizer is not available for version < 4.0.0"
        tokenizer = AutoTokenizer.from_pretrained(model_type)

    return tokenizer
```

[log.txt](https://github.com/Tiiiger/bert_score/files/10095673/log.txt)
Here is the log file, and the error information is at the end.

**Comment by felixgwu** [comment]
Hi @TristanAlkaid , 

You'll need to set the path for the tokenizer as well.
Assuming that you have downloaded `bert-base-chinese` in your folder `/home/zxy/SportsSum/model/`
There will be two files `tokenizer.json` and `tokenizer_config.json` in this folder.
You can need to load the model and tokenizer from this folder by this:
```
model_type = "/home/zxy/SportsSum/model/"

model = get_model(model_type)
tokenizer = get_tokenizer(model_type)
```

To use bert score, you can simply do
```
from bert_score import BERTScorer

scorer = BERTScorer(model_type="/home/zxy/SportsSum/model/", num_layers=8)
P, R, F1 = scorer.score(cands, refs)
```

**Comment by TristanAlkaid** [comment]
Hi @felixgwu ,
Thank you so much! ! ! That's a great help for me!
