### ISSUE TITLE
inputs format & running warning

### ISSUE THREAD

**Issue by JingsenZhang** [Tiiiger/bert_score#146]
Hi Tianyi!
    Happy new year~
    I really appreciate your work “BERTSCORE: EVALUATING TEXT GENERATION WITH BERT", and hope to use it in my project.
    However, I have a few questions to be answered:
    1. Is the input formats BERTScore supports  just like this:
    [“today is a good day”, “the weather is great"]   
    And how about the following format:
    [[‘today’, ‘is’, ‘a’, ‘good’, ‘day’], [‘the’, ‘weather’, ‘is’, ‘great’]]
    2. When I run the score() function, a warning rises as:

“Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.bias', 'lm_head.bias', 'lm_head.dense.weight', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).”
    How can I handle it?
    Hope to get your answer, thank you！

**Comment by Tiiiger** [comment]
Hi @JingsenZhang 

We don't expect tokenized input because the underlying pretrained models will tokenize in their own way. You can convert the tokens into a string for scoring. 

The error message you are seeing is a benign warning and not related to the question.
