### ISSUE TITLE
A negative rescaled value

### ISSUE THREAD

**Issue by JingsenZhang** [Tiiiger/bert_score#152]
Hi Tianyi!
I really appreciate your work, and hope to use it in my project.
However, I'm a little confused: 
I used it as follows, and got some negative score values, which you introduced in the document that this is possible. 
And I would like to know what is the reason for the negative value, because the normal rescaled value will be between 0 and 1, because Is the default baseline inaccurate for my data?
Is there any solution, or just keep this form？
Thank you for your answer!

<img width="989" alt="截屏2023-03-14 09 58 02" src="https://user-images.githubusercontent.com/36886184/224873669-51c7afb8-e119-4788-8d12-fc13f80cbe67.png">

**Comment by JingsenZhang** [comment]
In addition, 
I found that the same batch of data occasionally has slightly different calculated score values (for example, the first time is 24.5612%, the second time is 24.5614%), 
but the BLEU and ROUGE indicators corresponding to this batch of data are unchanged. 
Is that reasonable?

**Comment by Tiiiger** [comment]
Hi @JingsenZhang I think this menas that your pairs are less similar than two random sentence. 

What is the BLEU score you get?

**Comment by JingsenZhang** [comment]
Thank you for your reply. I think so. By adjusting the hyperparameters and increasing the number of training rounds, the indicator is now positive.

**Comment by JingsenZhang** [comment]
Thank you for your reply. I think so. 
By adjusting the hyperparameters and increasing the number of training rounds, the bert-score is now positive.

**Comment by JingsenZhang** [comment]
Thank you for your reply. 
I think so. The bleu value is very low and close to 0.
By adjusting the hyperparameters and increasing the number of training rounds, the bert-score is now positive.

**Comment by JingsenZhang** [comment]
> In addition, I found that the same batch of data occasionally has slightly different calculated score values (for example, the first time is 24.5612%, the second time is 24.5614%), but the BLEU and ROUGE indicators corresponding to this batch of data are unchanged. Is that reasonable?

**AND how about this problem? Thank you.**

**Comment by Tiiiger** [comment]
I am unclear. can you provide a minimal reproducing example?

**Comment by Tiiiger** [comment]
And please read the blogpost https://github.com/Tiiiger/bert_score/blob/master/journal/rescale_baseline.md


it is not lower bounded by 0.

**Comment by JingsenZhang** [comment]
> And please read the blogpost https://github.com/Tiiiger/bert_score/blob/master/journal/rescale_baseline.md
> 
> it is not lower bounded by 0.

I've read the blogpost, so maybe getting negative values is because "Base" is not reliable?

**Comment by Tiiiger** [comment]
No, a negative value here means that the similarity you get is less than that of two random sentences. 

Also matches up with the fact that your BLEU score is near zero.

**Comment by JingsenZhang** [comment]
> No, a negative value here means that the similarity you get is less than that of two random sentences.
> 
> Also matches up with the fact that your BLEU score is near zero.

Ok, I see, that means 0 indicates the similarity of two random sentences. Thanks!

**Comment by JingsenZhang** [comment]
> I am unclear. can you provide a minimal reproducing example?

This is the case, I used bert_score and bleu to evaluate the similairy between text generated by generative model and the reference text. And i set the fixed seed, occasionally the bert score is slightly different, but the bleu is always the same. 

I'll give you an simple example next time I come across. Thank you.
