### ISSUE TITLE
Model and Tokenizer change

### ISSUE THREAD

**Issue by sajjadIslam2619** [Tiiiger/bert_score#167]
Hello, 

I appreciate your fantastic work. I have looked into the paper and the project, especially the example/demo files. I am curious to know if is there any way to change the model and tokenizer such as clinical-BERT in the bert_score library. 

Thanks, 
Sajjad

**Comment by felixgwu** [comment]
Hi @sajjadIslam2619,

You may set `--model_type medicalai/ClinicalBERT` and set the layer that you want to use to compute bertscore like  `--num_layers 4`. To pick which layer to use, you may take a look at our example https://github.com/Tiiiger/bert_score/tree/master/tune_layers. However, our tuning dataset is based on general text not clinical data, so the best layer may not be accurate.

Best,
Felix

**Comment by sajjadIslam2619** [comment]
Thanks @felixgwu :)
