### ISSUE TITLE
How to handle Index Error Issue 

### ISSUE THREAD

**Issue by ShauryaUppal-1Mg** [Tiiiger/bert_score#17]
Should I trim the string to 512 or I can increase the maximum sequence length or something. 
![Screenshot 2019-10-10 at 10 33 48 PM](https://user-images.githubusercontent.com/47315683/66590423-5ab29280-ebae-11e9-8510-e3e2ed475ca0.png)
![Screenshot 2019-10-10 at 10 34 22 PM](https://user-images.githubusercontent.com/47315683/66590425-5d14ec80-ebae-11e9-885e-a4700d89b9b9.png)
![Screenshot 2019-10-10 at 10 34 38 PM](https://user-images.githubusercontent.com/47315683/66590429-5edeb000-ebae-11e9-8d65-1d7a3568ff7f.png)

**Comment by ShauryaUppal-1Mg** [comment]
@Tiiiger

**Comment by felixgwu** [comment]
Hi @ShauryaUppal-1Mg,

Thank you for using our BERTScore.
The reason for this error is that both BERT and RoBERTa are trained with sentences with at most 512 tokens. Unlike the original Transformers, BERT and RoBERTa use learned positional embedding whose size is set during training.
BERTScore is commonly computed between a pair of sentences.
We would suggest that you split the documents into sentences before feeding them to BERT.
If there happen to be some sentences with more than 512 tokens, you can:
1) train a BERT model using longer sentences
2) cut sentences into multiple chunks and design a better way to aggregate them. This is one of the future directions to extend BERTScore, but we haven't studied it yet.
3) use XLNets which support longer inputs. However, they perform worse in our experiments.

Best,
Felix

**Comment by ShauryaUppal-1Mg** [comment]
Will if work will it for sentence having length > 512, I remove stopwords and common words?

**Comment by ShauryaUppal-1Mg** [comment]
But BERT as a service allows user to make max_sequence= ignore 
Can't we do something with that? 

https://github.com/hanxiao/bert-as-service

**Comment by felixgwu** [comment]
As far as know, they just trim down the sequence. Please see:
https://github.com/hanxiao/bert-as-service/blob/85690491d66fd1ca0d03924f8c9ead3d1cad90b1/server/bert_serving/server/__init__.py#L414-L422

We would like to follow huggingface's transformers and just raise an error.
We encourage users to deal with their own special cases. 

Thank you for raise this issue. We will update the README to remind other users.
