### ISSUE TITLE
score函数无法加载离线模型【已解决】

### ISSUE THREAD

**Issue by XuJianzhi** [Tiiiger/bert_score#179]
本来是 model_type 参数就行，但是  https://github.com/Tiiiger/bert_score/blob/master/bert_score/score.py#L236   中 model_type 作为key，所以，可以自己改。
从 https://github.com/Tiiiger/bert_score/blob/master/bert_score/utils.py#L40 查是多少，而做替换即可。

**Comment by dt-yuhui** [comment]
请问离线模型位置放在哪里？我替换了还是报错
