### ISSUE TITLE
Unreasonably high cosine similarity between words

### ISSUE THREAD

**Issue by Relento** [Tiiiger/bert_score#20]
Hi! I tried to run the model with version 0.2.1, but found that the cosine similarity between different words are unreasonably high, as in the example:
![image](https://user-images.githubusercontent.com/23029424/68729206-3287cc00-057e-11ea-95dc-2a354517a924.png)
generated from 
```
bert-score-show --lang en -r "it is freezing today" -c "the weather is cold today" -f out.png
```
where the minimum similarity between any two words is greater than 0.8, different from the stats in the paper, which is
![image](https://user-images.githubusercontent.com/23029424/68729561-2f411000-057f-11ea-99e2-d0ab7106f2e4.png)

Also the last figure in the google codalab link https://colab.research.google.com/drive/1kpL8Y_AnUUiCxFjhxSrxCsc6-sDMNb_Q#scrollTo=UW1Nku_LMjzg has the same problem
I am wondering what may be the problem? Thanks!

**Comment by Tiiiger** [comment]
@Relento the range of the cosine similarity depends on the model you used to compute it. 

The plot in the paper is computed from a bert-base model while this command is computing using the roberta-large model. In other words, I don't think there is an error. 

I will update the README to specify this point. Thank you for letting me know.

**Comment by Relento** [comment]
@Tiiiger  Thank you for your prompt reply! I have tried bert-base and bert-large for this testcase and the output seems good. But I am still wondering the performance with roberta-large, because the BERTScore F1 calculated with roberta-large on my dataset has 10x smaller variance compared to bert-base.

**Comment by Tiiiger** [comment]
hi @Relento, thank you for giving us the heads up. I just confirmed this phenomenon on our datasets. This is indeed intriguing. Seems like BERTScore computed with RoBERTa simply has a smaller range. We are looking into why this is happening.

**Comment by Tiiiger** [comment]
I am closing this issue for now. In case you have more questions, you can continue under this thread.

**Comment by Tiiiger** [comment]
hi @Relento , in #23 we have a fix for this problem.

**Comment by chikubee** [comment]
Hi @Tiiiger , I just tested BertScore with two sentences using bert-base-uncased and roberta, and they have an unexpected high similarity. Is this the expected behaviour?
Sentence 1. How to reset phone
Sentence 2. How to reset dog
Sentence 3. How to reset password

Sentence1 and Sentence2 are highly similar.
while Sentence1 and Sentence3 are not so similar. 

How do you support this?
