### ISSUE TITLE
Support for P-Means layer weighting

### ISSUE THREAD

**Issue by sarahwie** [Tiiiger/bert_score#21]
Hi, are you planning to or willing to share the code from Appendix C for using P-Means to select the best representation for the model when no validation data exists for layer selection?

Thanks for the open-sourced code & extensive ablation experiments in the paper.

**Comment by Tiiiger** [comment]
hi @sarahwie, to be honest, we didn't plan this. but now that you mention it, I don't see a reason why we shouldn't do it. I'll try to clean the codes this weekend and push. If you want to implement it, feel free to open a PR.

**Comment by sarahwie** [comment]
Thanks! If I can tomorrow, I'll implement it & submit a PR.

**Comment by Tiiiger** [comment]
hi @sarahwie, sorry for a late update on this. 

As we showed in Appendix C and reported by concurrent work, P-MEANS is potentially a useful technique to improve the representation quality. Unfortunately it introduces several hyper-parameters (e.g. the layers of representations being aggregated, the "power" of the embeddings). Meanwhile, we have not conducted a large-scale study on the effect of P-MEANS as we did for other techniques in BERTScore. Therefore, we don't plan on including this method into our repo.

If you're still interested, feel free to fork and implement it in your own branch. You may want to modify the input embeddings to this function https://github.com/Tiiiger/bert_score/blob/master/bert_score/utils.py#L255.

Again, thank you for your interest in BERTScore.
