### ISSUE TITLE
request for the data in Image Captioning experiment

### ISSUE THREAD

**Issue by ChrisRBXiong** [Tiiiger/bert_score#22]
Hi, would you mind release the data used in Image Captioning experiment (human judgments of twelve submission entries from the COCO 2015 Captioning Challenge) in your paper? Thanks a lot!

**Comment by felixgwu** [comment]
Hi @ChrisRBXiong,

We follow the setup of [Learning to Evaluate Image Captioning](https://arxiv.org/abs/1806.06422). 
The human scores are from the COCO [leaderboard](http://cocodataset.org/#captions-leaderboard). You'll see the M1 & M2 human scores if you click the "Challenge2015" button.
You may contact the authors if you have additional questions regarding their setting.

Best,
Felix

**Comment by GaryYufei** [comment]
Hi, just a follow here. Any idea about how to get those system outputs?

**Comment by felixgwu** [comment]
Hi @GaryYufei,

Please contact the authors of [Learning to Evaluate Image Captioning](https://arxiv.org/abs/1806.06422) for the data set and experimental setup.

Best,
Felix

**Comment by GaryYufei** [comment]
Thanks Felix.

Yufei

**Comment by GaryYufei** [comment]
I am sorry @felixgwu, but I got no reply from the authors of "Learning to Evaluate Image Captioning". I think I understand all the setup from that paper and the only missing data is the system outputs on COCO 2014 Val Set (I think it should [here](http://lsun.cs.princeton.edu/), but it seems to be down). Any pointers?

**Comment by felixgwu** [comment]
Hi @GaryYufei, Here is a link to the val set outputs: https://drive.google.com/file/d/1HUrcgLXTNUY9ZbJ6eegb2V92Hfh17j9e
I hope this helps.

**Comment by GaryYufei** [comment]
Cool. That's exactly what I want! Thank you very much

**Comment by PierreColombo** [comment]
@GaryYufei were you able to reproduce the results ?
I got 40k captions where in the MoverScore paper they mention 5k examples

**Comment by yavuzdrmzksr** [comment]
Hi @felixgwu, I downloaded the val set outputs from the link you provided (https://drive.google.com/file/d/1HUrcgLXTNUY9ZbJ6eegb2V92Hfh17j9e). As far as I can see, "junhua.mao" and "mRNN_share.JMao" submissions have the same outputs. Are those submissions correct? In Figure 7 of "Learning to Evaluate Image Captioning" paper they state they compute different results for "m-RNN" and "m-RNN (Baidu/ UCLA)".
