### ISSUE TITLE
BERT Score for Elastic Search

### ISSUE THREAD

**Issue by simonefrancia** [Tiiiger/bert_score#24]
Hello,
I am trying to integrate lots of documents from different languages inside ElasticSearch;
a big difficulty for me is to use a stable method to embed all the BERT hidden outputs inside one unique vector in order to compute a significant similarity between them.
My aim is to add this BERTscore inside the function that searches for similar document, given a query document. 
Actually is use this in elasticSearch:

```
script_query = {
        "script_score": {
            "query": {"match_all": {}},
            "script": {
                "source": "cosineSimilarity(params.query_vector, doc['text_vector']) + 1.0",
                "params": {"query_vector": query_vector}
            }
        }
    }
```
and I used the meanPooling in order to unify all the layers output in only one but it doesn't seem to work well .
Do you think that bertScore could be a good idea? Does the score work also on other languages?

Another point is that we already have a optimized system that calculates BERT embedding and we should only attach the bert score calculus in the output. Can it work for you? 
Thanks

```

**Comment by Tiiiger** [comment]
hi @simonefrancia 

> I used the meanPooling in order to unify all the layers output in only one but it doesn't seem to work well.

In my experience, tuning the choice of layer(s) to use is very important. The final few layers of these pre-trained transformers usually don't yield good performance. For BERTScore, we tune this choice on some machine translation evaluation dataset. 

> Do you think that BERTScore could be a good idea?

I believe neither my collaborators nor I have actually tested BERTScore for elastic search and document retrieval in general. So, unfortunately, I don't have a confident answer for this.

> Does the score work also on other languages?

Yes! Compute BERTScore with multilingual BERT. It supports 104 languages. For reference, see https://github.com/google-research/bert/blob/master/multilingual.md

>  we should only attach the bert score calculus in the output

https://github.com/Tiiiger/bert_score/blob/master/bert_score/utils.py#L218

This function in `utils.py` takes pre-computed embeddings and computes the greedy matching score between two sequences. You can adapt this for your use.

**Comment by Tiiiger** [comment]
Closing for now but feel free to continue the thread for further questions.
