### ISSUE TITLE
Execute demo.py should only wait for download?

### ISSUE THREAD

**Issue by zysNLP** [Tiiiger/bert_score#25]
I use python demo.py to test your model. It occur some bars show me to download .json and so on.
I have a slow network speed. So I want to ask if I can copy some web page, and offline download?

**Comment by Tiiiger** [comment]
hi @zysNLP I believe you are seeing the progress bar to download the BERT model. You can try run the transformers library first and download the pre-trained model you want to work with.

You can try our [colab](https://colab.research.google.com/drive/1kpL8Y_AnUUiCxFjhxSrxCsc6-sDMNb_Q#scrollTo=6cOBG7xyMjy_) example where the model will be downloaded through Google's network.
