### ISSUE TITLE
Running slowly

### ISSUE THREAD

**Issue by HqWu-HITCS** [Tiiiger/bert_score#3]
Hi, Thank you for your nice work and release code, I have tried to run the code, but it is very slow, may be i should change some setting? Could you give me some advice ? Thank you very much~

**Comment by Tiiiger** [comment]
Are you running on a GPU or a CPU?

**Comment by HqWu-HITCS** [comment]
Thank you~

Runing on a GPU? 
Maybe like this:
    CUDA_VISIBLE_DEVICES=0 bert-score -r example/refs.txt -c example/hyps.txt --bert bert-base-uncased
But it seems don't work...



wuhuanqin@foxmail.com
 
From: Tianyi
Date: 2019-04-26 22:43
To: Tiiiger/bert_score
CC: hqWu; Author
Subject: Re: [Tiiiger/bert_score] Running slowly (#3)
Are you running on a GPU or a CPU?

**Comment by Tiiiger** [comment]
Can you benchmark the speed? How many sentences are you running? How long is each sentence? How long does it take you? 

We will add a progressbar in the next version of this codebase.

**Comment by HqWu-HITCS** [comment]
> Can you benchmark the speed? How many sentences are you running? How long is each sentence? How long does it take you?
> 
> We will add a progressbar in the next version of this codebase.

Thank you~

I am running the example you give:
CUDA_VISIBLE_DEVICES=0 bert-score -r example/refs.txt -c example/hyps.txt --bert bert-base-uncased
Actually， there is a progressbar when running the code. as show from the progressbar, I need 6h40min42sec. In addition, I meet a error as follow:

Traceback (most recent call last):
  File "/home/.../anaconda3/bin/bert-score", line 11, in <module>
    load_entry_point('bert-score==0.1.0', 'console_scripts', 'bert-score')()
  File "/home/.../anaconda3/lib/python3.6/site-packages/cli/score.py", line 46, in main
    model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'

**Comment by Tiiiger** [comment]
The progress bar (we have right now) will be shown when you are downloading the BERT model. If it takes 6h+, I would suggest checking your internet configuration. Can you upload a screenshot of all the output when you are running the example script? 

This error suggests that the model is not downloaded correctly or the BERT configuration is misspelled. Can you let me know if you still encounter this problem after you download the BERT model successfully?

**Comment by Tiiiger** [comment]
Hi @HqWu-HITCS, I have added a [colab example](https://colab.research.google.com/drive/1kpL8Y_AnUUiCxFjhxSrxCsc6-sDMNb_Q) that might be easier for you to run. 

Try running this if you want to get a taste of BERTScore. 

For future use, you can make a copy of the demo notebook and modify for your use. Colab comes with a free GPU (K80) which should be enough for most cases.

**Comment by HqWu-HITCS** [comment]
Thank you very much~


I will try it soon.


Thany you angain~




 
---Original---

**Comment by Tiiiger** [comment]
I am closing for now. In case you have more questions, please feel free to reopen this issue.

**Comment by pasana** [comment]
Hi, I have just noticed that the `score` function download and load model at each call and there is no caching for roberta thought it may be the most used model. Is there any specific reason for that ?

**Comment by Tiiiger** [comment]
hi @pasana, thank you for your interest in our repo. 

Your description is correct about that the `score` function will load the model (any model you'd like to use) every time you call the function. However, the `score` function will not re-download the model. 

Re downloading: 

I'd like to get your help in double checking this behavior. If you can confirm that you are re-downloading the model every you use `score`, can you provide a minimal code snippet to replicate it?

My suspicion is that this re-downloading will not happen. Nevertheless, if it does occur, I suggest you to look into whether you have turn on some non-default behaviors of the hugging face `transformer` library. 

Re loading the model: 

Yes I understand that the overhead of creating a new model and moving it to GPU can be significant. It is our top priority to better cache the model in the next iteration of this repo, which likely would happen _by the end of February_.

That being said, I suggest to reduce the number of calls to the `score` function. For example, combine multiple calls by merging the input candidate and reference pairs into two large list of strings when possible.

**Comment by nicofirst1** [comment]
> Yes I understand that the overhead of creating a new model and moving it to GPU can be significant. It is our top priority to better cache the model in the next iteration of this repo, which likely would happen by the end of February.

Has this issue been addressed?
