### ISSUE TITLE
small readme edit

### ISSUE THREAD

**Issue by cainesap** [Tiiiger/bert_score#31]
Hello,
Thank you for the great resource!
A small edit to the readme where it says:

Starting from versino 0.3.0, we support rescaling the scores with baseline scores
```sh
bert-score -r example/refs.txt -c example/hyps.txt --lang en
```

-- I think should be:
Starting from version 0.3.0, we support rescaling the scores with baseline scores
```sh
bert-score -r example/refs.txt -c example/hyps.txt --lang en --rescale-with-baseline
```

(?)
Andrew

**Comment by felixgwu** [comment]
Hi @cainesap,
Thanks a lot for pointing out the typo! I've fixed it.

Best,
Felix
