### ISSUE TITLE
why L2 normalize each feature?

### ISSUE THREAD

**Issue by riven314** [Tiiiger/bert_score#32]
Thanks for repo! 

My question refers to the following code snippet from ```score.py```:  
```
ref_embedding.div_(torch.norm(ref_embedding, dim=-1).unsqueeze(-1))
hyp_embedding.div_(torch.norm(hyp_embedding, dim=-1).unsqueeze(-1))
```

From what I understand from the code, you tried to L2-normalize each word embedding features across all tokens in a sentence. After that, you calculate similarity score matrix. 

Would you mind explaining the rationale of doing the normalization?

**Comment by Tiiiger** [comment]
hi @riven314 , Thank you for your interest. 

BERTScore relies on the *cosine similarity* between the token representations. Cosine similarity is one common and popular metric for embeddings and we adopt it in BERTScore. L2-normalization is a required step in computing BERTScore. 

We have conducted a study on this note specifically and our conclusion is that L2-normalization can improve the quality of BERTScore (in the sense of improving human correlation). Unfortunately, we did not include this in the paper as of now. 

Hope this resolve your confusion.
