### ISSUE TITLE
Pandas verison

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [Tiiiger/bert_score#34]
Hi, thanks for your wonderful works.

I notice that the `rescaling` attribute need the `pandas` version higher than `0.23`, which is not clear in the README. So I raise the issue for you.

Hope you have a good day.

**Comment by Tiiiger** [comment]
hi @gmftbyGMFTBY thank you for the heads-up. 

I have updated the requirement in https://github.com/Tiiiger/bert_score/commit/df3108064ca4243a94d0b67f292503ff806ba8b0
