### ISSUE TITLE
Load once, run every time

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [Tiiiger/bert_score#36]
Hi, thank you for your helpful repo.

During using your wonderful works, I found that it's a little unsatisfied to use the `score` function in the python script.

In my work, I usually need to measure the performance of lots of datasets. But the `score` function always loads the model weights first and then run the evaluation, which is very time-consuming. So I think if you can add the function to load the model weights first (for example `.load_weight(path)` function of the BERTScore object) and then use it to evaluate the performance, which will be much better and faster.

Hope to get your responses about this suggestion.

**Comment by Tiiiger** [comment]
hi @gmftbyGMFTBY, 

Yes we are going to support this feature soon. In fact, it has been already added in the `oop` branch. You build from source and try out the `Scorer` object  (https://github.com/Tiiiger/bert_score/blob/oop/bert_score/scorer.py) for now.

We're adding documentation and examples. Once those are done, we will upload to `pip`.

**Comment by Tiiiger** [comment]
this is implemented in `0.3.1` now
