### ISSUE TITLE
Negative score

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [Tiiiger/bert_score#37]
Hi, thank you for your helpful repo.

During using the `score` function (with rescaling), I find sometimes it generates the negative scores which makes me confused (in the paper, the score is range from 0 and 1). In my processing, I just ignore the negative scores, but I still think it is not suitable.

In your [explanantions](https://github.com/Tiiiger/bert_score/blob/master/journal/rescale_baseline.md), the negative scores is calculated after the BERTScore. But I'm not sure what is the negative scores' meaning, can you provide me the meaning of negative scores?

Hope to get your responses about this suggestion.

**Comment by Tiiiger** [comment]
Hi @gmftbyGMFTBY, 

As the blog post explains, the baselines are computed on pairs of random sentences. If you get negative scores, it means this: the similarity of your candidate-reference pair is worse than that of a random pair. In practice, this happened rarely to me when testing common WMT translation datasets. 

I also want to note that before rescaling, the theoretical range of BERTScore is also not between 0 and 1. It is between -1 and 1, the same as the range of cosine similarity. 

I am still curious about your use case here. What kind of data and generation model are you working with? What are the BLEU, ROUGE scores you typically see on this data? This information will be very helpful for me to help you pinpoint the problem. 

However, if you do observe 'many' negative scores, I suspect that there are other issues (e.g. bugs) going on.

**Comment by gmftbyGMFTBY** [comment]
Ok, thanks, close it.

**Comment by manikbhandari** [comment]
Hi, I had a doubt regarding the theoretical range of BERTScore. I understand that the cosine similarity can be between -1 and 1 but I see in the implementation that during padding, the mask is given a value of 0 ([here](https://github.com/Tiiiger/bert_score/blob/2f84c6cada6b0b7a397df4aa41860c7a6edd6e70/bert_score/utils.py#L199)) and the mask is used to filter out the similarity [here](https://github.com/Tiiiger/bert_score/blob/2f84c6cada6b0b7a397df4aa41860c7a6edd6e70/bert_score/utils.py#L347). So if my understanding is correct, whenever there is padding in a batch, the theoretical minimum for BERTScore is 0?

Thanks :)
