### ISSUE TITLE
How to use bert_score with multiply references ?

### ISSUE THREAD

**Issue by liesun1994** [Tiiiger/bert_score#42]
Hi ,  thanks for the releasing of bert_score !  I'm trying to use bert_score with multi-references. As you mentioned above ,  the code supports multi-references right now . So how to use bert_score with multi-references ? 
Example is listed as follows:
`bert-score -r example/refs.txt -c example/hyps.txt --lang en`
How to change refs.txt to multi-refs ?

**Comment by felixgwu** [comment]
Hi @liesun1994,

Thanks for you question. We just updated the command line code to support multiple references.
With the newest code, you can do:
`bert-score -r refs_1.txt refs_2.txt refs_3.txt -c hyps.txt --lang en`
where `refs_1.txt`, `refs_2.txt`, and `refs_3.txt` are your reference files.

If you have 1000 candidates, then each of these reference files has 1000 lines.
The first lines of `refs_1.txt`, `refs_2.txt`, and `refs_3.txt` correspond to the first candidate in `hyps.txt`.

Please install the newest code in the master branch of this Github repo.
I hope this answers your question.

Best,
Felix

**Comment by liesun1994** [comment]
THX! I will try it !

**Comment by liesun1994** [comment]
It works ! Thanks ! @felixgwu
