### ISSUE TITLE
strangely high scores w/ BERTScore 

### ISSUE THREAD

**Issue by danyaljj** [Tiiiger/bert_score#43]
I am getting some pretty high scores for trivial inputs; take the following example: 

```python 
(bert_score_p, bert_score_r, bert_score_f) = bert_score.score(cands=["a"], refs=["some random string"], lang='en')
print((bert_score_p, bert_score_r, bert_score_f))
```

The output is: 
```
(tensor([0.8874]), tensor([0.8125]), tensor([0.8483]))
```
which are pretty high scores. What am I missing here?

**Comment by Tiiiger** [comment]
hi @danyaljj , thank you for your interest in this package. 

This is indeed a frequently asked question. I kindly refer you to the blog post I wrote [here](https://github.com/Tiiiger/bert_score/blob/master/journal/rescale_baseline.md).
