### ISSUE TITLE
How to get rescale_baseline tsv files with my data? 

### ISSUE THREAD

**Issue by liesun1994** [Tiiiger/bert_score#44]
Hi, I am trying to use `bert_score` with other pretrained models, whose rescale_baseline files  are not provided in your code,  so how to get those tsv files with my models .  This issue is mentioned as [https://github.com/Tiiiger/bert_score/blob/master/journal/rescale_baseline.md](url)

**Comment by liesun1994** [comment]
@Tiiiger

**Comment by Tiiiger** [comment]
hi @liesun1994 ,

First of all, what model are you trying out?

Second, to get those tsvs, you basically need to follow the procedure described in that [journal](https://github.com/Tiiiger/bert_score/blob/master/journal/rescale_baseline.md)
```
For each language, we select a million sentences from some large monolingual corpus. 
We randomly group sentences into candidate-reference pairs, resulting in half a million pairs. 
For each contextual embedding model, we compute BERTScore on the random pairs and take the average to be the baseline. 
```

For more details, I used the monolingual corpuses in CommonCrawl. 

I do not have clean code that I am ready to share but I am happy to chat more if you're stuck. 

And if you do get a clean python script to compute these, you are more than welcome to contribute through a PR. 

Leaving this open as I understand you may want to follow up.

**Comment by liesun1994** [comment]
Sorry for late reply, thanks a lot @Tiiiger . I will try the steps you mentioned above !

**Comment by Tiiiger** [comment]
Closing now. Let me know if you have more questions.
