### ISSUE TITLE
The download speed is very slow in China

### ISSUE THREAD

**Issue by chncwang** [Tiiiger/bert_score#53]
After I execute bert_score to run examples, it begins to download files, and the first file is downloaded fast, but the second file of size 1.43G, which I suppose is the BERT model file, is very verty slow, and my base is China. Is there any method to work around this problem? for example can I download BERT models elsewhere first and then use bert_score to run them?

**Comment by felixgwu** [comment]
Hi @chncwang,

It seems to be common that it's very slow to download files from s3 to China.
Since the model downloading part is handled within [huggingface's transformers](https://github.com/huggingface/transformers) library, it would be better to contact them instead.


To use a downloaded model with `bert-score`, you can simply set `--model path/to/my/roberta-large` to specify the folder containing the pretrained model.

Best,
Felix

**Comment by chncwang** [comment]
Thank you!

**Comment by felixgwu** [comment]
Hi @chncwang,

I've put a copy of RoBERTa-large on Baidu Pan. I hope this helps.
Link: https://pan.baidu.com/s/1MTmGHsZ3ubn7Vr_W-wyEdQ 
Password: dhe5

Best,
Felix

**Comment by chncwang** [comment]
> Hi @chncwang,
> 
> I've put a copy of RoBERTa-large on Baidu Pan. I hope this helps.
> Link: https://pan.baidu.com/s/1MTmGHsZ3ubn7Vr_W-wyEdQ
> Password: dhe5
> 
> Best,
> Felix

Many thanks! i am just struggling to search where to download bert models satisfying bert_score's format, but have not seen  anywhere. I will try it right now!

**Comment by chncwang** [comment]
> Hi @chncwang,
> 
> I've put a copy of RoBERTa-large on Baidu Pan. I hope this helps.
> Link: https://pan.baidu.com/s/1MTmGHsZ3ubn7Vr_W-wyEdQ
> Password: dhe5
> 
> Best,
> Felix

It works!
Would you mind to facilitate me to download bert-base-chinese please? Since I plan to use bert-score to evaluate conversation models on Chinese. Thank you again!

**Comment by felixgwu** [comment]
Yes, here is the link: https://pan.baidu.com/s/1THfiCXjWtdGGsCMskQ5svA and password: jvk7
I hope this helps.

**Comment by chncwang** [comment]
It really helps me! Thank you again!

**Comment by chncwang** [comment]
Despite various ngram and embedding based automatic metric approaches I have tried, this is the first automatic metric showing our models' priority. It really saves me...
