### ISSUE TITLE
Semantic vs Syntactic

### ISSUE THREAD

**Issue by zeeqy** [Tiiiger/bert_score#54]
Hi, Looks like position matters more than semantic meanings?

I came across this example

Initial with `BERTScorer(lang="en", rescale_with_baseline=True)`

Case1
```
cands = 'city in canada'
refs = ['city in china']
BERTScore = 0.6102
```

Case2
```
cands = 'city in canada'
refs = ['canadian city']
BERTScore = 0.0938
```

Should Case2 have better score than Case1? Or did I miss some critical settings?

**Comment by felixgwu** [comment]
Hi @zeeqy,

Yes, this is an interesting observation. I believe this is related to the fact that BERT/RoBERTa captures syntactic very well. [Ian et. al.](https://arxiv.org/pdf/1905.05950.pdf) also found that pre-trained BERT captures several syntactic features well. I believe this the outcome of the mask language modeling task used for pre-training.

Similar to what you show, we also present some cases where BERTScore fails in Table 7 in our paper. As we can see in Table 3, the correlation with human judgments is still not close to 1 yet. While BERTScore outperforms previously existing metrics, there is definitely some space for future work to improve upon. We hope some more advanced pre-training methods in the future can provide us better contextual embeddings that capture semantic well.

**Comment by zeeqy** [comment]
Very clear, thanks. I'm closing this issue.
