### ISSUE TITLE
can the source sentence be incorperated into contextual embeddings?

### ISSUE THREAD

**Issue by chncwang** [Tiiiger/bert_score#56]
When evaluating conversation models using bert-score, a natural idea is that is is beneficial to add the source sentence before both the hypothesis and the reference to form better contextual embeddings. But when calculating cosine similarity, the source sentence should not be involved.

**Comment by Tiiiger** [comment]
hi @chncwang , sorry for a late reply, neurips deadline : )

Yes I imagine this would be possible but I am not sure how popular this demand is. Feel free to fork this repo and implement it!

Let me know if you have any question about the code.

**Comment by chncwang** [comment]
Thank you all the same!

**Comment by chncwang** [comment]
> hi @chncwang , sorry for a late reply, neurips deadline : )
> 
> Yes I imagine this would be possible but I am not sure how popular this demand is. Feel free to fork this repo and implement it!
> 
> Let me know if you have any question about the code.

Thank you all the same!
