### ISSUE TITLE
Comparing splitted wordpiece tokens

### ISSUE THREAD

**Issue by Lukecn1** [Tiiiger/bert_score#57]
Hi there, 

Thank you for releasing this repo and for the development of the metric.  

I was wondering how are you handling cases when an OOV word is split into different pieces by the word-piece tokenizer used in BERT models? 

Specifically, when you are comparing the embedding vectors for the tokens in a candidate-reference sentence pair, are you doing any preemptive pooling of vectors for splitted words before you run the cosine similarity, or do you leave them as is?

**Comment by Tiiiger** [comment]
hi @Lukecn1 thank you for you interest.

We leave the subword pieces as it is and just treating them as a normal token.

**Comment by Lukecn1** [comment]
Alright, thank you for the quick answer.
