### ISSUE TITLE
Does BERT-Score support larger Chinese BERT models

### ISSUE THREAD

**Issue by chncwang** [Tiiiger/bert_score#59]
I find BERT-Score correlate much better with human evaluation when evaluating conversation.
Specifically, it seems scores rated by higher layers are better than lower layers. So I really want to see scores with higher layers than 12.

**Comment by Tiiiger** [comment]
yes technically it does. 

however there isn't a release `bert-large-chinese` model, at least not included in the huggingface transformers model (**https://huggingface.co/transformers/pretrained_models.html**).

If you happen to have access to some large Chinese pre-trained models, you can use these models by specifying the path to the pre-trained models in the `model_type` argument when calling the `score` function.

You can check the specification here https://github.com/Tiiiger/bert_score/blob/master/bert_score/score.py#L51
