### ISSUE TITLE
Scores are nan when cands/refs lists have one element

### ISSUE THREAD

**Issue by shoegazerstella** [Tiiiger/bert_score#6]
Hello, 
I am trying this simple example here:

```
cands = ['hello how are you?'] 
refs = ['hello how are you?'] 
P, R, F1 = score(cands, refs, bert="bert-base-uncased", verbose=True)
P: tensor([nan])
R: tensor([nan])
F1: tensor([nan])
```

I noticed that if the list of cands/refs has only one element, the resulting scores are nan.
This does not happen when len(cands) > 1.
I was curious on why this happens. Thanks a lot!

**Comment by Tiiiger** [comment]
Hello there, 
thank you for pointing this out. I will fix it today.

**Comment by Tiiiger** [comment]
Please turn off idf scaling by calling
```
cands = ['hello how are you?'] 
refs = ['hello how are you?'] 
P, R, F1 = score(cands, refs, bert="bert-base-uncased", verbose=True, no_idf=True)
```

Otherwise, all of the IDF scores would be 0 because there is only 1 reference sentence. I have added a tip to the README for future users. 

Again, thank you for letting me know.
