### ISSUE TITLE
Critical assumption leads to erroneous results

### ISSUE THREAD

**Issue by ozancaglayan** [Tiiiger/bert_score#63]
Hi,

I've been getting unexpectedly high scores for some settings which I couldn't reproduce then. Only to find out in the code that, if `-c <candidate>` does not exist as a file, the script does not error and assumes that `<candidate>` is not a path but a sentence. It also assumes that the references are no longer paths but sentences as well. If there's some overlap between the characters of `<candidate>` path and reference paths, you get a decent bertscore around 0.60.

I think this is quite a dangerous issue

**Comment by Tiiiger** [comment]
hi @ozancaglayan , 

thank you for pointing this out! we will look into how best to fix this.

**Comment by ozancaglayan** [comment]
A simple fix would be to add a boolean flag which will tell the code whether the arguments to `-c` and `-r` are strings rather than file paths.

**Comment by felixgwu** [comment]
I'm closing this issue since it has been addressed in a recent commit.
https://github.com/Tiiiger/bert_score/commit/cfd4d560f7832e6ed7d8d2387b5baa22fd2979d8
