### ISSUE TITLE
Get final weighted average

### ISSUE THREAD

**Issue by datistiquo** [Tiiiger/bert_score#64]
Am I right that you just get back the individual score for each pairwise token?

For getting the final (weighted) average of each candidate to each reference I need to do this by myself?

**Comment by Tiiiger** [comment]
hi @datistiquo , 

if you are using the python interface, then yes. You need to compute the mean by yourself.

**Comment by datistiquo** [comment]
Hey, thanks. Is it the same in the main code, I mean here:

https://github.com/Tiiiger/bert_score/blob/master/bert_score/score.py

**Comment by Tiiiger** [comment]
hi yes, this is the behavior of `bert_score.score` function.

if you are using the command line interface, we do print the average score of all pairs.

**Comment by datistiquo** [comment]
Hey thank,

I very desperately try to implement this score by myself and tried different things to optimize like map and list comprehension and last but not least I used the faster tensor multiplication from tensorflow (like the same for pytorch). But it is very slow. I have 300 examples for queries and references each and I need on a 4 core CPU i7 arond 30s... That is really bad. Do you know how fast is your bert score?

Do you know how long your implementation is for roughly the number of examples I wrote above? Is it really so slow?

Thank you!

**Comment by Tiiiger** [comment]
Do you still need help? seems like you have figured out the question. 

Also I am just curious, why do you feel that you need to reimplement instead of using our repo? Is there some kind of constraint that you have to use tensorflow?
