### ISSUE TITLE
How to output standard deviations

### ISSUE THREAD

**Issue by chncwang** [Tiiiger/bert_score#65]
Hi, it seems bert-score outputs mean values only, any option to enable standard deviations?

**Comment by chncwang** [comment]
or just outputs the bert-score of every hypothesis.

**Comment by tianyi-asapp** [comment]
hi @chncwang , 

if you take a look at our [demo](https://github.com/Tiiiger/bert_score/blob/master/example/Demo.ipynb), you can use the python function `bert_score.score` to get the outputs of the bert-score of every pair.
