### ISSUE TITLE
 bert_score version in demo on Google Colab should be changed. 

### ISSUE THREAD

**Issue by mhmohona** [Tiiiger/bert_score#70]
On the [demo on Google Colab](https://colab.research.google.com/drive/1kpL8Y_AnUUiCxFjhxSrxCsc6-sDMNb_Q) link given in ReadMe.md the command is used to install bert_score is `pip install bert_score==0.2.0`; if I run the command it is showing error:

> ERROR: Could not find a version that satisfies the requirement bert_score==0.2.0 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4)
> ERROR: No matching distribution found for bert_score==0.2.0

![error](https://user-images.githubusercontent.com/14244685/87698844-dc76c280-c7b5-11ea-9d6f-05c845ebfc5e.PNG)

It should be `pip install bert_score==0.3.4` to make the cell perfectly.

![working perfect](https://user-images.githubusercontent.com/14244685/87699028-121bab80-c7b6-11ea-8e59-587dfb654e9a.PNG)

**Comment by Tiiiger** [comment]
hi @mhmohona, Good Catch! I will fix it right away.
