### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by nandinib1999** [Tiiiger/bert_score#73]
Hi,

I have been trying to use BertScore as an evaluation parameter for fine-tuning the sentence-transformers using SNLI data. (https://github.com/UKPLab/sentence-transformers) I have also have made changes in the code for usage. However, when I try to run the training script, I get **RuntimeError: CUDA out of memory.**  error when it is trying to calculate the embeddings of the sentences for greedy search.

So I wanted to ask if you have used BertScore for any such use case? Is there any workaround for the Memory Error?

**Comment by Tiiiger** [comment]
hi @nandinib1999 , please lower the `batch_size` for the `score` function.
