### ISSUE TITLE
Evaluating the Accuracy of BERT Score

### ISSUE THREAD

**Issue by dhimasyoga16** [Tiiiger/bert_score#76]
Let's say i have 500 pairs of question title which is saved in 2 separated files (question_title1.txt, question_title2.txt), i want to check the **similarity** of **each question** in question_title2.txt to **each question** in question_title1.txt.
My question is, how can i measure the accuracy of the BERT Score's performance on checking the similarity? Does BERT Score has a built in method to do this? Or maybe i need another "3rd party" library?

Thankyou in advance.

**Comment by varshakishore** [comment]
Currently, you would have to first create two new files that contain all possible pairs of questions that you want to compute a similarity score for. You can then use this library to get scores for every pair.

**Comment by dhimasyoga16** [comment]
Like what i've explain above, i have created 2 separated files to store all pairs of questions that i want to compute the similarity score, they are **question_title1.txt** and **question_title2.txt**. 
What i'm asking is how can i find out how accurate BERT Score is in computing similarity, or in other words : _how many pairs of questions that BERT Score can compute the similarity score correctly_

**Comment by Tiiiger** [comment]
Hi @dhimasyoga16 , you can refer to our paper to see how we have evaluated the accuracy of BERTScore. Essentially, you will need some kind of human annotation. You can either compute accuracy or correlation with regard to your human annotation. 

Given that this discussion is less relevant to the technical details of this repo, I am closing this issue. I am happy to continue this discussion under this issue.
