### ISSUE TITLE
Warning on Transformers version 

### ISSUE THREAD

**Issue by kojimano** [Tiiiger/bert_score#78]
I would like to use BERT score with the older versions of Transformers library (specifically version 2.3.0). 

At a glance, Transformers==2.3.0 seems to be working with bert_score without any problems. I would like to know if there is any known silent incompatibility between bert_score and Transformers library (OR simply Transformers <3.0.0 is just not tested).

Thanks in advance!

**Comment by Tiiiger** [comment]
we have been using transformers<=3.0.0 until #68 . 

I believe that 2.3.0 should work fine (after we have fixed #68). You can run our internal test https://github.com/Tiiiger/bert_score/blob/master/tests/test_score_function.py to see if the results match.

Thank you!
