### ISSUE TITLE
Evaluation Corpora

### ISSUE THREAD

**Issue by gmihaila** [Tiiiger/bert_score#79]
Thank you for your great work! 

Can you guys share the **Machine Translation** and **Image Captioning** corpora that contain **references**, **candidates** and **human scores** along with the **BLEU** and **Bert Score**?

Thank you!

**Comment by fwu-asapp** [comment]
Hi @gmihaila ,
You can find machine translation data from the [WMT18 website](http://www.statmt.org/wmt18/metrics-task.html) and the COCO data from previous issue #22.

**Comment by felixgwu** [comment]
Hi @gmihaila ,
You can find machine translation data from the [WMT18 website](http://www.statmt.org/wmt18/metrics-task.html) and the COCO data from previous issue #22.

**Comment by gmihaila** [comment]
> Hi @gmihaila ,
> You can find machine translation data from the [WMT18 website](http://www.statmt.org/wmt18/metrics-task.html) and the COCO data from previous issue #22.

Thank you for your reply @felixgwu !

Regarding the WMT18:
Where exactly can I find the humans scores in the [WMT18 website](http://www.statmt.org/wmt18/metrics-task.html)? I did find the [human evaluation data](http://computing.dcu.ie/~ygraham/newstest2018-humaneval.tar.gz) under [results](http://www.statmt.org/wmt18/results.html) but I'm not able to find any documentation on where to get the actual translation reference and candidates for those human scores... 😢 

Regarding the COCO dataset the link you showed me sent me to this drive link: https://drive.google.com/file/d/1HUrcgLXTNUY9ZbJ6eegb2V92Hfh17j9e I don't understand where exactly are the human scores? I only see BLEU, CIDEr, ROGUE and METEOR. I wasn't able to find any README for clarifications 😥 

I appreciate any help! 🙏

**Comment by felixgwu** [comment]
For COCO, we use the system-level human scores from the [leaderboard](https://cocodataset.org/#captions-leaderboard).
If you click the Challenge2015 button, you'll see M1 and M2 which are used as the human scores.
We follow the experimental setup of [Learning to Evaluate Image Captioning](https://arxiv.org/abs/1806.06422). You may read this paper or contact the corresponding authors for more details.

For WMT18, we use [wmt18-metrics-task-full.tgz](http://ufallab.ms.mff.cuni.cz/~bojar/wmt18/wmt18-metrics-task-full.tgz).

**Comment by gmihaila** [comment]
Thank you @felixgwu! The WMT18 is still confusing to me. I will spend more time and try to figure it out.

**Comment by felixgwu** [comment]
You can also see our [example](https://github.com/Tiiiger/bert_score/tree/master/tune_layers) for evaluating the model on WMT16 data which is our validation set. I hope it helps.

**Comment by gmihaila** [comment]
> You can also see our [example](https://github.com/Tiiiger/bert_score/tree/master/tune_layers) for evaluating the model on WMT16 data which is our validation set. I hope it helps.

wow this is exactly what I was looking for! Thank you so much! 🙏 

How come this script does not work for WMT18? 🤔

**Comment by Tiiiger** [comment]
hi @gmihaila I think this probably is just a different in the path pattern?

What kind of error do you see when you run the script for WMT18 data?

**Comment by gmihaila** [comment]
> hi @gmihaila I think this probably is just a different in the path pattern?
> 
> What kind of error do you see when you run the script for WMT18 data?

Thank you @Tiiiger!

I am using the [get_wmt16](https://github.com/Tiiiger/bert_score/blob/3dc3e3d43af3c7ccc068d3a0ace744cee4c38a26/tune_layers/tune_layers.py#L14) from [example](https://github.com/Tiiiger/bert_score/tree/master/tune_layers) mentioned by @felixgwu .

This is the snippet I use in my notebook for wmt16:

```python
!wget -q -nc https://www.computing.dcu.ie/~ygraham/wmt16-metrics-results.tar.gz
!tar -xf wmt16-metrics-results.tar.gz

import os

def get_wmt16(lang_pair, data_folder="wmt16"):
    with open(
        os.path.join(
            data_folder,
            f"wmt16-metrics-results/seg-level-results/DAseg-newstest2016/DAseg-newstest2016.human.{lang_pair}",
        )
    ) as f:
        gold_scores = list(map(float, f.read().strip().split("\n")))

    with open(
        os.path.join(
            data_folder,
            f"wmt16-metrics-results/seg-level-results/DAseg-newstest2016/DAseg-newstest2016.reference.{lang_pair}",
        )
    ) as f:
        all_refs = f.read().strip().split("\n")

    with open(
        os.path.join(
            data_folder,
            f"wmt16-metrics-results/seg-level-results/DAseg-newstest2016/DAseg-newstest2016.mt-system.{lang_pair}",
        )
    ) as f:
        all_hyps = f.read().strip().split("\n")

    return gold_scores, all_refs, all_hyps

gold_scores, all_refs, all_hyps = get_wmt16(lang_pair='cs-en', data_folder='.')
```

And it works great!

**BUT** when I try to use this code for WMT18 It does not work...

```python
!wget -q -nc http://ufallab.ms.mff.cuni.cz/~bojar/wmt18-metrics-task-package.tgz
!tar -xf wmt18-metrics-task-package.tgz

import os

def get_wmt18(lang_pair, data_folder="wmt18"):
    with open(
        os.path.join(
            data_folder,
            f"wmt18-metrics-task-package/seg-level-results/DAseg-newstest2018/DAseg-newstest2018.human.{lang_pair}",
        )
    ) as f:
        gold_scores = list(map(float, f.read().strip().split("\n")))

    with open(
        os.path.join(
            data_folder,
            f"wmt18-metrics-task-package/seg-level-results/DAseg-newstest2018/DAseg-newstest2018.reference.{lang_pair}",
        )
    ) as f:
        all_refs = f.read().strip().split("\n")

    with open(
        os.path.join(
            data_folder,
            f"wmt18-metrics-task-package/seg-level-results/DAseg-newstest2018/DAseg-newstest2018.mt-system.{lang_pair}",
        )
    ) as f:
        all_hyps = f.read().strip().split("\n")

    return gold_scores, all_refs, all_hyps

gold_scores, all_refs, all_hyps = get_wmt18(lang_pair='cs-en', data_folder='.')
```

I get a path error: 

```bash
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-21466379e2b5> in <module>()
     31     return gold_scores, all_refs, all_hyps
     32 
---> 33 gold_scores, all_refs, all_hyps = get_wmt18(lang_pair='cs-en', data_folder='.')

<ipython-input-2-21466379e2b5> in get_wmt18(lang_pair, data_folder)
      8         os.path.join(
      9             data_folder,
---> 10             f"wmt18-metrics-task-package/seg-level-results/DAseg-newstest2018/DAseg-newstest2018.human.{lang_pair}",
     11         )
     12     ) as f:

FileNotFoundError: [Errno 2] No such file or directory: './wmt18-metrics-task-package/seg-level-results/DAseg-newstest2018/DAseg-newstest2018.human.cs-en'
```

I can't figure out how to change the path from your wmt16 codeto work with wmt18. All files inside wmt18 look so different from wmt16...

**Comment by felixgwu** [comment]
Thank you for your questions. This seems to be a question regarding the WMT18 dataset instead of BERTScore. It would be better for you to directly contact the organizers of WMT18 to fully understand the task and how the data are stored instead of directly asking for a solution from us.
To avoid accidentally giving people some misinformation about the dataset, we currently do not plan to provide supports for the datasets in this repo.

**Comment by gmihaila** [comment]
In your paper it says you used WMT18. That is the why i kept asking for the code that worked for wmt18.

*Machine Translation Our main evaluation corpus is the WMT18 metric evaluation dataset (Ma et al., 2018), which contains predictions of 149 translation systems across 14 language pairs, gold references, and two types of human judgment scores*

I do appreciate both of your help!
