### ISSUE TITLE
Recall and F1 are nan

### ISSUE THREAD

**Issue by shoegazerstella** [Tiiiger/bert_score#8]
Hi, 
Any idea why I get R and F1 equal to nan when I do this:

``` 
    cands = ['hi how is going?', 'hi my name is Stella']
    refs = ['hi how are you?', 'hi how are you?']

    no_idf = True if len(refs) == 1 else False
    P, R, F = score(cands, refs, bert="bert-base-multilingual-cased", no_idf=no_idf)
    
    P: [0.75812787 0.55651724]
    R: [nan nan]
    F1: [nan nan]

```

**Comment by tianyi-asapp** [comment]
Hi, you need to put `no_idf=True` because the two reference sentences are the same. 

I understand that this is very counterintuitive. We are working on improving it.

**Comment by Tiiiger** [comment]
Hi, 

please turn `no_idf=True` because both of your reference sentences are the same.

I understand that this is very counterintuitive. We are working on improving it.

**Comment by shoegazerstella** [comment]
Thanks a lot, it works now.
So `no_idf` should be True if the reference sentences are the same and also if refs contain just one element.
