### ISSUE TITLE
Version update changes the scores

### ISSUE THREAD

**Issue by ozancaglayan** [Tiiiger/bert_score#81]
Hi there,

Going from v0.3.4 (transformers=2.11) to v0.3.6 (transformers=3.3.1) shifts the scores abruptly for a given system:

```
roberta-large_L17_no-idf_version=0.3.6(hug_trans=3.3.1)-rescaled P: 0.294713 R: 0.474827 F1: 0.376573
roberta-large_L17_no-idf_version=0.3.4(hug_trans=2.11.0)-rescaled P: 0.459102 R: 0.514197 F1: 0.479780
```

**Comment by Tiiiger** [comment]
hi @ozancaglayan 

Looking into this right now

**Comment by Tiiiger** [comment]
@ozancaglayan 

what examples are you testing this? can you identify a few sentences where the scores changed and post them here?

Currently I can pass our internal tests. 

Thank you!

**Comment by ozancaglayan** [comment]
is it possible to see the output of tokenizer? I have `<unk>`s in my files, can that be the issue?

**Comment by Tiiiger** [comment]
@ozancaglayan 

yes you can see the output of the tokenizer. A easier way to do this might be just to load the tokenizer yourself.

for example
```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer("roberta-large")
```

Let me know if you found anything

**Comment by ozancaglayan** [comment]
I've tested with these 10 sentences and the results do not match as well:

`candidate file`
```
<unk> man with <unk> red helmet on <unk> small moped on <unk> dirt road
<unk> young girl inhales with the intent of blowing out <unk> candle
<unk> man on <unk> bicycle riding next to <unk> train
<unk> kitchen is shown with <unk> variety of items on the counters
<unk> wooden ball on top of <unk> wooden stick
multiple wooden spoons are shown on <unk> table top
<unk> bathroom that has <unk> broken wall in the shower
<unk> bathroom with an enclosed shower next to <unk> sink and <unk> toilet
people on bicycles ride down <unk> busy street
the bathroom is clean and ready to be used
```

`reference file`
```
a man with a red helmet on a small moped on a dirt road
a young girl inhales with the intent of blowing out a candle
a man on a bicycle riding next to a train
a kitchen is shown with a variety of items on the counters
a wooden ball on top of a wooden stick
multiple wooden spoons are shown on a table top
a bathroom that has a broken wall in the shower
a bathroom with an enclosed shower next to a sink and a toilet
people on bicycles ride down a busy street
the bathroom is clean and ready to be used
```

**Comment by Tiiiger** [comment]
Tokenizing the first sentence.

with `transformers==2.11.0`
['<unk>', 'Ġman', 'Ġwith', '<unk>', 'Ġred', 'Ġhelmet', 'Ġon', '<unk>', 'Ġsmall', 'Ġm', 'oped', 'Ġon', '<unk>', 'Ġdirt', 'Ġroad']

with `transformers==3.3.1`
['<unk>', 'Ġman', 'Ġwith', 'Ġ', '<unk>', 'Ġred', 'Ġhelmet', 'Ġon', 'Ġ', '<unk>', 'Ġsmall', 'Ġm', 'oped', 'Ġon', 'Ġ', '<unk>', 'Ġdirt', 'Ġroad']

This seems to be a weird issue with the roberta byte-level tokenizer. let me check the huggingface repo

**Comment by felixgwu** [comment]
Hi @ozancaglayan,
The inconsistency comes from the `<unk>` token in your candidate file. Huggingface changes the behavior of RoBERTaTokenizer on the `<unk>` since v3.0.0. Based on the official tokenizer of RoBERTa in fairseq, it doesn't have a process a special `<unk>`. Instead, it treats it as a normal word and splits it into multiple BPE tokens. Therefore, the behavior of calculating BERTScore with `<unk>` is undefined and should be avoided.

Notably, the meaning of an unknown token can vary with different tokenizers, so the unknown word output from your system shouldn't be treated as an unknown word of RoBERTa. In general, we suggest not use any special token in your candidate files.

**Comment by ozancaglayan** [comment]
Thanks, but I found this a bit more trickier. What if we have such token in our candidate files? Or at least, I think this should be documented in the README file. People can have such tokens in their outputs for several reasons. I think there should be at least one consistent token that is never splitted out and kept as it is.
