### ISSUE TITLE
Getting key error for score.py in bert_score

### ISSUE THREAD

**Issue by Souravroych** [Tiiiger/bert_score#82]
Iam trying to fine tune bert-base-uncased using tf2

![Screen Shot 2020-10-30 at 2 44 31 PM](https://user-images.githubusercontent.com/51218100/97751995-9c6bef00-1ac9-11eb-903b-0c33f9e6e74b.png)

**Comment by Tiiiger** [comment]
hi @Souravroych when you use a custom model that is not in the huggingface repo, we do not have a default hyperparameter to use. 

You need to specify the layer value to the `score` function.
