### ISSUE TITLE
`score` function failed with the new `transformers` v4.0.0

### ISSUE THREAD

**Issue by kirzharov** [Tiiiger/bert_score#85]
**What I did:**
Try to get scores with `score` function

**Actual result:**
Get the error: `'RobertaTokenizerFast' object has no attribute 'max_len'`

**Expected result:**
`score` function work as before and get results

**More details:**
* `bert_score` version: `0.3.6`
* `transformers` version: `4.0.0`
* Python version: `3.8`

_Context:_
* Release notes for the new `transformers` version: https://github.com/huggingface/transformers/releases/tag/v4.0.0
* PR with removing `max_len` attribute from `transformers` package: https://github.com/huggingface/transformers/pull/8604

_Previous warning:_
The `max_len` attribute has been deprecated and will be removed in a future version, use `model_max_length` instead.

**Comment by kirzharov** [comment]
Hi guys! I added a PR with hotfix for this issue and when I creating a PR I saw similar one: #84 😀

**Comment by kirzharov** [comment]
For those who will need to use the `bert_score` version before this fix (for example: `0.3.6`, `0.3.5`, .etc):

Just add `transformers==3.5.1` to your `requirements.txt` file or install before installing previous `bert_score` version with `pip install transformers==3.5.1` or just update with `pip install -U transformers==3.5.1` (if you have installed `transformers ` or  `bert_score` before)

Link to the comment from similar issue in `transformers` repo: https://github.com/huggingface/transformers/issues/8739#issuecomment-733927199

**Comment by davebulaval** [comment]
> Hi guys! I added PR with a hotfix for this issue: #86, and when I created a PR, I saw a similar one: #84

tks for the help on the fix.

**Comment by felixgwu** [comment]
This is resolved. Please use the code in our master branch for now. We will update the pypi package soon.
