### ISSUE TITLE
Ways to specify the model download path? 

### ISSUE THREAD

**Issue by serenayj** [Tiiiger/bert_score#89]
Hi, I want to specify the model (BERT) download path when I install bert-score. I tried doing "pip install bert-score -t /path/", It worked for this particular command, but when I did "bert-score -r example/refs.txt -c example/hyps.txt --lang en", it automatically started download something (roberta-large model I believe) to a default path, which is not where I want it to be. Could you point me to the lines of codes where you have the download command so that I could modify the download path? Thanks.

**Comment by Tiiiger** [comment]
https://github.com/Tiiiger/bert_score/blob/3dad430eb966fb5e4c1e158a968bf2a8d5f23fe6/bert_score/utils.py#L137

hi @serenayj you would want to add arguments to this line here
