### ISSUE TITLE
Error when scoring big text 

### ISSUE THREAD

**Issue by paulowiz** [Tiiiger/bert_score#90]
Hi I'm Trying to use a demo for getting scores between a list of pairs where they are big text and I got the error below.

cands =  df['company_description'][0:5]
refs =  df['abstract_training'][0:5] 
P, R, F1 = score(cands, refs, lang='en', verbose=True)

![image](https://user-images.githubusercontent.com/18649504/106611311-96613080-6546-11eb-9d5e-3a1e7d4a1b89.png)

Can you help me?

**Comment by Tiiiger** [comment]
@paulowiz can you paste me the input in this issue or upload your batch somewhere so I can reproduce the error?

also, which version of `bert_score` are you using?

**Comment by paulowiz** [comment]
last version

**Comment by Tiiiger** [comment]
can you provide a minimal example so I can reproduce the bug?

**Comment by Tiiiger** [comment]
closing for now if there is no further questions.
