### ISSUE TITLE
the running is always terminated

### ISSUE THREAD

**Issue by lytum** [Tiiiger/bert_score#91]
Hi,

I am running BERTScorer(lang="en", rescale_with_baseline=True) or score(hypothese, list_of_reference, lang='en', verbose=True) to get the bertscore. However, it's always automatically terminated. like:

computing bert embedding.
 80%|███████████████████████████████████▎        | 2933/3649 [31:22<05:13,  2.28it/s]

maintain the 80% precent and no more future running.  

Do you have any suggestion for this kind of situation?

Thanks for any feedback.

**Comment by Tiiiger** [comment]
hi @lytum 

you probably run out of RAM? Can you check that? For example, through `htop`

**Comment by lytum** [comment]
> hi @lytum
> 
> you probably run out of RAM? Can you check that? For example, through `htop`

I run this with GPU, the memory shows enough. Do you have some suggestion for that? the dataset includes 300k sentences, I guess it's too much.

**Comment by lytum** [comment]
> hi @lytum
> 
> you probably run out of RAM? Can you check that? For example, through `htop`

it seems you are right. It's true GPU is necessary to compute BERTScore.

**Comment by lytum** [comment]
I finally found the above problem is caused by dataset, where there are some very long sentences. After removing those datas, the issue is solved.
