### ISSUE TITLE
Cache Model if Possible

### ISSUE THREAD

**Issue by karinseve** [Tiiiger/bert_score#92]
At the following lines the model is read from file at every iteration of the `score' function.
It should be possible to cache it so that multiple subsequent calls do not need to read from file at every call of the function.

https://github.com/Tiiiger/bert_score/blob/732ff34992cd44852c2486d301a93c2a601ea166/bert_score/score.py#L152-L155

**Comment by felixgwu** [comment]
Hi @karinseve, if you want to use the same model multiple times, please consider using a `BERTScorer` object which caches the model and baseline values.
https://github.com/Tiiiger/bert_score/blob/732ff34992cd44852c2486d301a93c2a601ea166/bert_score/scorer.py#L29-L68

**Comment by felixgwu** [comment]
I'm closing this issue now, but please feel free to reopen it if you have other questions.
