### ISSUE TITLE
mT5

### ISSUE THREAD

**Issue by danyaljj** [Tiiiger/bert_score#93]
Thanks for the nice package! 

From the readme, I see that you have tried T5. Wondering if you have tried mT5 at all? If so, would be great to mention it in the readme (and the spreadsheet of the scores).

**Comment by felixgwu** [comment]
Hi @danyaljj, thanks for your suggestion. We just added 4 mT5 models to the spreadsheet.

**Comment by danyaljj** [comment]
This is great! Thanks for the quick update!

**Comment by liesun1994** [comment]
> Hi @danyaljj, thanks for your suggestion. We just added 4 mT5 models to the spreadsheet.

Wow , that would be nice!!!
