### ISSUE TITLE
Question: Using Vokenization with BERTScore

### ISSUE THREAD

**Issue by FelixLabelle** [Tiiiger/bert_score#95]
I'd like to use a RoBERTa model trained using [vokenization](https://arxiv.org/pdf/2010.06775.pdf) to score similarity between short phrases containing objects (e.g., the red staircase, the tiled floor).

The [vokenized models](https://github.com/airsplay/vokenization#models) use HuggingFace transformers, so I tried swapping the model after initializing the BERTScorer object. The results were, subjectively, not very good .

This may have been due to a tokenizer mismatch, so I'm in the process of running experiments where the [tokenizer is the same](https://github.com/airsplay/vokenization/blob/e5368bc13612408a8a80e06666bf65cbea096402/tokenization/tokenize_wiki_roberta.bash). Below is a code snippet of how replacing the default model with a vokenized one was done.

`
class VokenizationScorer(BERTScorer):
    def __init__(self,*args,**kwargs):
        # Init BERTScorer
        super().__init__(*args,**kwargs)
        # Load config
        self.config = AutoConfig.from_pretrained('./checkpoint-last/config.json')
        # Init vokenized model and replace BERTScorer Model
        state_dict = torch.load('checkpoint-last/pytorch_model.bin')
        self._model.from_pretrained(None,config=self.config,state_dict=state_dict)
        self._model.to(self.device)
        # Init and replace tokenizer
        self._tokenizer = AutoTokenizer.from_pretrained('roberta-base')
        
 
vokenization = True
if vokenization:
    scorer = VokenizationScorer(lang="en", device="cuda:3")
`

Besides a tokenizer mismatch, are there any other possible sources of issues (e.g. HF library version mismatches, internal assumptions about the model,etc..)?

**Comment by Tiiiger** [comment]
hi @FelixLabelle ,

I don't think so. 

are you sure they are using the `roberta-base` tokenizer? I thought they are using `bert-base` tokenizers, not sure cased or uncased.

**Comment by FelixLabelle** [comment]
@Tiiiger Hmm, that's good point.. Swapping the Tokenizer to `roberta-base` did make lead to an improvement (subjectively), but the results are still not exactly as expected.

I've asked the question on their github and will update this post once I know more. In the mean-time I will try with the `bert-base-uncased` tokenizer, based on your comment and [this line of code](https://github.com/airsplay/vokenization/blob/5601b799184ed54414872565f233e22c76f5f6f0/vokenization/vokenization.py#L326).

**Comment by Tiiiger** [comment]
Besides the tokenizer, I don't really see what can go wrong. Perhaps Vokenizer model is not suited for bertscore but I don't have a good intuition for that.
