### ISSUE TITLE
Is text truncation to 512 tokens handled automatically for both candidate and reference texts?

### ISSUE THREAD

**Issue by wingedRuslan** [Tiiiger/bert_score#96]
Hi,

I wanted to clarify the following information. On the README page, you mention that 

> Limitation: Because BERT, RoBERTa, and XLM with learned positional embeddings are pre-trained on sentences with max length 512, BERTScore is undefined between sentences longer than 510 (512 after adding [CLS] and [SEP] tokens). The sentences longer than this will be truncated. Please consider using XLNet which can support much longer inputs.

In my case, both *generated text* and *reference text* are longer than 512 tokens. While computing the BERTScore, will it automatically truncate **both** generated text and reference text to fit the requirement and then calculate the score between truncated versions of generated text and reference text? Or do I need to cut the length of generated text and reference text manually before calling the function to calculate BERTScore? 

Many thanks in advance,
Ruslan

**Comment by felixgwu** [comment]
Hi @wingedRuslan,

Yes, **both** generated text and reference text are truncated automatically. 
Different models may have different maximum lengths. Please check out this [sheet](https://docs.google.com/spreadsheets/d/1RKOVpselB98Nnh_EOC4A2BYn8_201tmPODpNWu4w7xI/edit#gid=0) for the maximum length supported by each model.
For example, you may consider BART, Longformer, or LED models, which support longer text.

Best,
Felix

**Comment by wingedRuslan** [comment]
@felixgwu thanks a lot for clarifying this!

**Comment by fzl8888** [comment]
为什么在我的情况下是没有自动truncation？ RuntimeError: The expanded size of the tensor (514) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [2, 514].  Tensor sizes: [1, 512]
