### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by Hbenmazi** [Tiiiger/bert_score#97]
When I use the bert-score command, I get an error:
UnicodeDecodeError:'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128).

How can I fix it ?

**Comment by Tiiiger** [comment]
https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte


Which python version are you using? Also, maybe check this link to see if it is relevant.

**Comment by Tiiiger** [comment]
Closing for now because of inactivity.
