### ISSUE TITLE
Question: how to get the best reference 

### ISSUE THREAD

**Issue by AStenco** [Tiiiger/bert_score#98]
Hi, 

thank you for your job! I'm trying to use bert_score with multireferences, but as I understood, the result is the best score among the references. It's not clear to me if there is a way to get also the relative reference or if I need to put hand to code to get that result as well.

Thank you in advance!

**Comment by felixgwu** [comment]
Hi, it is not supported in our codebase current.
Here are the lines where it gets the best score among references.
https://github.com/Tiiiger/bert_score/blob/master/bert_score/score.py#L141-L145

I think you can modify it to
```python
    if ref_group_boundaries is not None:
        max_preds = []
        best_ref_index = []
        for beg, end in ref_group_boundaries:
            max_preds.append(all_preds[beg:end].max(dim=0)[0])
            best_ref_index.append(all_preds[beg:end].ag=argmax(dim=0))
        all_preds = torch.stack(max_preds, dim=0)
```
`best_ref_index` would contain the index of the best reference for each set of references.

**Comment by Tiiiger** [comment]
Closing now due to inactivity.

**Comment by AStenco** [comment]
Sorry, I forgot to give you a feedback. That worked! Thank you for the quick answer and still sorry for the lack of a feedback.
